robotTesting/urls.py
from django.conf.urls import url
from django.contrib import admin
from front.views import home, testsList, lastResults, robotSettings, show_result, show_test
from api.views import startTesting, testStatus, testKill

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home),
    url(r'^tests-list/', testsList),
    url(r'^last-results/', lastResults),
    url(r'^settings/', robotSettings),
    url(r'^start/', startTesting),
    url(r'^status/', testStatus),
    url(r'^stop/', testKill),
    url(r'^results/(.*)/(.*)/', show_result),
    url(r'^robot-test/(.*)/(.*)/', show_test),
]

front/forms.py
from django import forms

class SettingsForm(forms.Form):
    git_repo = forms.CharField(max_length=100)
    test_path = forms.CharField(max_length=100)
    sel_host = forms.GenericIPAddressField(protocol='IPv4')
    sel_port = forms.IntegerField(max_value= 60000, min_value = 1024)
    browser = forms.CharField(max_length=100)
    sel_os = forms.CharField(max_length=100)
    git_user = forms.CharField(max_length=100)
    git_pass = forms.CharField(max_length=100)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Robot tests</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    {% include "css.html" %}
</head>

<body>
    <div class="wrapper">
    {% include "sidebar.html" %}
        <div class="main-panel">
        {% include "navbar.html" %}
            {% block content %} {% endblock %}
            {% include "footer.html" %}
        </div>
    </div>
</body>
{% include "js.html" %}


{% block script %} {% endblock %}

<!-- <script type="text/javascript">
    $.notify({
        icon: "nc-icon nc-android",
        message: "Welcome to Robot."
    }, {
        type: 'info',
        timer: 8000,
    });
</script> -->

</html>

templates/css.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/light-bootstrap-dashboard.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/demo.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}" />

templates/dashboard.html
{% extends "base.html" %}

{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <div class="card ">
                    <div class="card-header ">
                        <h4 class="card-title">Last Run</h4>
                        <p class="card-category">Tests Statistics</p>
                    </div>
                    <div class="card-body ">
                        <div id="chart" class="ct-chart ct-perfect-fourth"></div>
                    </div>
                    <div class="card-footer ">
                        <div class="legend">
                            <i class="fa fa-circle text-success"></i> Pass |
                            <i class="fa fa-circle text-danger"></i> Fail 
                        </div>
                        <hr>
                        <div class="stats">
                            <!-- <i class="fa fa-clock-o"></i> Last run: 2 days ago -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card  card-tasks">
                    <div class="card-header ">
                    </div>
                    <div class="card-body table-full-width table-responsive">
                            {% for folder, tests in folders %}
                            <h4 class="card-title">{{folder}}</h4>
                            <table class="table table-hover">
                                <thead>
                                    <th>Name</th>
                                    <th>Log</th>
                                    <th>Status</th>
                                </thead>
                                <tbody>
                                        {% for test, result in tests.items%}
                                    <tr>
                                        <td>{{test}} </td>
                                        <td><a href="/results/{{folder}}/{{test}}"><i class="fa fa-folder-open-o"></i> Open log</a></td>
                                        <td>Passed: {{result.1.passed}} | Failed: {{result.0.failed}}</td>
                                    </tr>
                                        {% endfor %}
                                </tbody>
                            </table>
                            <hr>
                            <br>
                            {% endfor %}
                        
                        </div>
                </div>
            </div>
        </div> 
    </div>
</div>
{% endblock %}



{% block script %}
<script type="text/javascript">
    $(document).ready(function(){
        var data = { 
            series: [{
                    value: {{passed}},
                    name: 'passed',
                    className: 'test-passed',
                    },{
                    value: {{failed}},
                    name: 'failed',
                    className: 'test-failed',
            }] 
        };

        var options = {
            donutWidth: 40,
            startAngle: 270,
            showLabel: true,
        };
        Chartist.Pie('#chart', data, options);
    })
</script>
{% endblock %}

templates/footer.html
<footer class="footer">
                <div class="container">
                    <nav>
                        <ul class="footer-menu">
                            <li>
                                <a href="/">
                                    Home
                                </a>
                            </li>
                            <!-- <li>
                                <a href="/">
                                    Company
                                </a>
                            </li>
                            <li>
                                <a href="/">
                                    Portfolio
                                </a>
                            </li>
                            <li>
                                <a href="/">
                                    Blog
                                </a>
                            </li> -->
                        </ul>
                        <p class="copyright text-center">
                            ©
                            <script>
                                document.write(new Date().getFullYear())
                            </script>
                            <a href="#">Robot</a>
                        </p>
                    </nav>
                </div>
            </footer>

templates/home.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

    {% include "css.html" %}
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Dashboard</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Settings</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Help</a>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    </header>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link active" href="#">Overview <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Reports</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Analytics</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Export</a>
            </li>
          </ul>

          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link" href="#">Nav item</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Nav item again</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">One more nav</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Another nav item</a>
            </li>
          </ul>

          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link" href="#">Nav item again</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">One more nav</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Another nav item</a>
            </li>
          </ul>
        </nav>

        <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
          <h1>Dashboard</h1>

          <section class="row text-center placeholders">
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAAJ12AAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <div class="text-muted">Something else</div>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAADcgwAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAAJ12AAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-6 col-sm-3 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIABAADcgwAAACwAAAAAAQABAAACAkQBADs=" width="200" height="200" class="img-fluid rounded-circle" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
          </section>

          <h2>Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>libero</td>
                  <td>Sed</td>
                  <td>cursus</td>
                  <td>ante</td>
                </tr>
                <tr>
                  <td>1,004</td>
                  <td>dapibus</td>
                  <td>diam</td>
                  <td>Sed</td>
                  <td>nisi</td>
                </tr>
                <tr>
                  <td>1,005</td>
                  <td>Nulla</td>
                  <td>quis</td>
                  <td>sem</td>
                  <td>at</td>
                </tr>
                <tr>
                  <td>1,006</td>
                  <td>nibh</td>
                  <td>elementum</td>
                  <td>imperdiet</td>
                  <td>Duis</td>
                </tr>
                <tr>
                  <td>1,007</td>
                  <td>sagittis</td>
                  <td>ipsum</td>
                  <td>Praesent</td>
                  <td>mauris</td>
                </tr>
                <tr>
                  <td>1,008</td>
                  <td>Fusce</td>
                  <td>nec</td>
                  <td>tellus</td>
                  <td>sed</td>
                </tr>
                <tr>
                  <td>1,009</td>
                  <td>augue</td>
                  <td>semper</td>
                  <td>porta</td>
                  <td>Mauris</td>
                </tr>
                <tr>
                  <td>1,010</td>
                  <td>massa</td>
                  <td>Vestibulum</td>
                  <td>lacinia</td>
                  <td>arcu</td>
                </tr>
                <tr>
                  <td>1,011</td>
                  <td>eget</td>
                  <td>nulla</td>
                  <td>Class</td>
                  <td>aptent</td>
                </tr>
                <tr>
                  <td>1,012</td>
                  <td>taciti</td>
                  <td>sociosqu</td>
                  <td>ad</td>
                  <td>litora</td>
                </tr>
                <tr>
                  <td>1,013</td>
                  <td>torquent</td>
                  <td>per</td>
                  <td>conubia</td>
                  <td>nostra</td>
                </tr>
                <tr>
                  <td>1,014</td>
                  <td>per</td>
                  <td>inceptos</td>
                  <td>himenaeos</td>
                  <td>Curabitur</td>
                </tr>
                <tr>
                  <td>1,015</td>
                  <td>sodales</td>
                  <td>ligula</td>
                  <td>in</td>
                  <td>libero</td>
                </tr>
              </tbody>
            </table>
          </div>
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    {% include "js.html" %}
  </body>
</html>

templates/js.html
{% load static %}
<script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/light-bootstrap-dashboard.js' %}" type="text/javascript"></script>
<script src="{% static 'js/demo.js' %}"></script>
<!-- plugins -->
<script src="{% static 'js/plugins/bootstrap-datepicker.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/bootstrap-notify.js' %}"></script>
<script src="{% static 'js/plugins/bootstrap-switch.js' %}"></script>
<script src="{% static 'js/plugins/chartist.min.js' %}"></script>
<script src="{% static 'js/plugins/nouislider.min.js' %}"></script>

templates/lastresults.html
{% extends "base.html" %}

{% block content %}
<div class="content">
                <div class="container-fluid">
                    <div class="row">
                            <div class="col-md-12">
                                    <div class="card card-plain table-plain-bg">
                                        <div class="card-header ">
                                            <!-- <h4 class="card-title">Last run results</h4> -->
                                        </div>
                                        <div class="card-body table-full-width table-responsive">
                                            {% for folder, tests in folders %}
                                            <p>{{folder}}</p>
                                            <table class="table table-hover">
                                                <thead>
                                                    <th>Name</th>
                                                    <th>Log</th>
                                                    <th>Status</th>
                                                </thead>
                                                <tbody>
                                                        {% for test, result in tests.items%}
                                                    <tr>
                                                        <td width="60%">{{test}} </td>
                                                        <td width="20%"><a href="/results/{{folder}}/{{test}}"><i class="fa fa-folder-open-o"></i> Open log</a></td>
                                                        <td width="20%">Passed: {{result.1.passed}} | Failed: {{result.0.failed}}</td>
                                                    </tr>
                                                        {% endfor %}
                                                </tbody>
                                            </table>
                                            <hr>
                                            <br>
                                            {% endfor %}
                                        
                                        </div>
                                    </div>
                                </div>
                    </div>              
                
                </div>
            </div>
{% endblock %}

templates/navbar.html
           <!-- Navbar -->
            <nav class="navbar navbar-expand-lg " color-on-scroll="500">
                <div class=" container-fluid  ">
                    <a class="navbar-brand" href="/"> Dashboard </a>
                    <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                        <ul class="nav navbar-nav mr-auto">
                            <li class="nav-item">
                                <a href="/" class="nav-link" data-toggle="dropdown">
                                    <span class="d-lg-none">Dashboard</span>
                                </a>
                            </li>
                            <li class="dropdown nav-item">
                                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                                    <i class="nc-icon nc-planet"></i>
                                    <span class="notification">5</span>
                                    <span class="d-lg-none">Notification</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <a class="dropdown-item" href="#">Notification 1</a>
                                    <a class="dropdown-item" href="#">Notification 2</a>
                                    <a class="dropdown-item" href="#">Notification 3</a>
                                    <a class="dropdown-item" href="#">Notification 4</a>
                                    <a class="dropdown-item" href="#">Another notification</a>
                                </ul>
                            </li>
                        </ul>
                        <!-- <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="no-icon">Menu</span>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <a class="dropdown-item" href="#">Something</a>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                    <div class="divider"></div>
                                    <a class="dropdown-item" href="#">Separated link</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#pablo">
                                    <span class="no-icon">Log out</span>
                                </a>
                            </li>
                        </ul> -->
                    </div>
                </div>
            </nav>
            <!-- End Navbar -->

templates/settings.html
{% extends "base.html" %}

{% block content %}
<div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="card ">
                                <div class="card-header ">
                                    <h4 class="card-title">New settings</h4>
                                    <p class="card-category">Enter new values and save them</p>
                                </div>
                                <div class="card-body ">
                                        <form method="post">
                                                {% csrf_token %}
                                                <div class="form-group">
                                                  <label for="id_git_repo">Git Repository</label>
                                                  <input type="text" class="form-control" id="id_git_repo" placeholder="Git repository" name="git_repo">
                                                  <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
                                                </div>
                                                <div class="form-group">
                                                  <label for="id_sel_host">Selenium HUB - IP</label>
                                                  <input type="text" class="form-control" id="id_sel_host" placeholder="Selenium HUB IP" name="sel_host">
                                                </div>
                                                <div class="form-group">
                                                        <label for="id_sel_port">Selenium HUB - PORT</label>
                                                        <input type="text" class="form-control" id="id_sel_port" placeholder="Selenium HUB PORT" name="sel_port">
                                                      </div>
                                                <div class="form-group">
                                                    <label for="id_sel_os">Selenium OS</label>
                                                    <input type="text" class="form-control" id="id_sel_os" name="sel_os" placeholder="Selenium OS (e.g.: LINUX)">
                                                </div>
                                                <div class="form-group">
                                                        <label for="id_test_path">Test Path</label>
                                                        <input type="text" class="form-control" id="id_test_path" name="test_path" placeholder="TEST_PATH env var">
                                                    </div>
                                                <div class="form-group">
                                                    <label for="id_git_user">Git User</label>
                                                    <input type="text" class="form-control" id="id_git_user" name="git_user" placeholder="Git User">
                                                </div>
                                                <div class="form-group">
                                                    <label for="id_git_pass">Git Password</label>
                                                    <input type="password" class="form-control" id="id_git_pass" name="git_pass" placeholder="Git Password">
                                                </div>
                                                <div class="form-check">
                                                    <label>Select browser:</label>
                                                    <br>
                                                    <label class="form-check-label">
                                                        <input class="form-check-radio" type="radio" name="browser" id="id_browser" value="chrome" checked>
                                                        Chrome
                                                    </label>
                                                    </div>
                                                    <div class="form-check">
                                                    <label class="form-check-label">
                                                        <input class="form-check-radio" type="radio" name="browser" id="id_browser" value="firefox">
                                                        Firefox
                                                    </label>
                                                </div>
                                                <br>
                                                <button type="submit" class="btn btn-primary">Save</button>
                                        </form>
                                    
                                </div>
                                <!-- <div class="card-footer ">
                                    <div class="legend">
                                        <i class="fa fa-circle text-success"></i> Pass |
                                        <i class="fa fa-circle text-warning"></i> Partial pass |
                                        <i class="fa fa-circle text-danger"></i> Fail |
                                    </div>
                                    <hr>
                                    <div class="stats">
                                        <i class="fa fa-clock-o"></i> Last run: 2 days ago
                                    </div>
                                </div> -->
                            </div>
                        </div>
                        <div class="col-md-6">
                                <div class="card ">
                                    <div class="card-header ">
                                        <h4 class="card-title">Current settings</h4>
                                        <!-- <p class="card-category">Current settings</p> -->
                                    </div>
                                    <div class="card-body ">
                                            <table class="table table-hover">
                                                    <thead>
                                                        <th>Setting</th>
                                                        <th>Value</th>
                                                    </thead>
                                                    <tbody>
                                                        {% for key, value in old_settings.items %}
                                                        <tr>
                                                            <td>{{ key }}</td>
                                                            <td>{{ value }}</td>
                                                        </tr>
                                                        {% endfor %}
                                                    </tbody>
                                                </table>
                                    </div>
                                </div>
                            </div>
                    </div> 
                </div>
            </div>
{% endblock %}

templates/show_result.html
{% block content %}
{{content | safe }}
{% endblock %}

templates/show_test.html
{% extends "base.html" %}

{% block content %}
<div class="content">
                <div class="container-fluid">
                    <div class="row">
                            <div class="col-md-12">
                                    <div class="card card-plain table-plain-bg">
                                        <div class="card-header ">
                                            <h4 class="card-title">{{name}}</h4>
                                            <hr>
                                        </div>
                                        <div class="card-body table-full-width table-responsive">
                                                <pre>{{content}}</pre>  
                                        </div>
                                    </div>
                                </div>
                    </div> 
                </div>
            </div>
{% endblock %}